:backgroundrb: 
  :ip: localhost
  :port: 21000
  :log: foreground

:schedules:
  :paypal_processor_worker: # Worker Name
    :refund: # Method Name
      :trigger_args: 0 1 1 * * * *
    :transfer:
      :trigger_args: 0 1 1 * * * *

      
# Scheduling:
# */10 * * * * * *  - Executes worker methods after every 10 seconds
# 0 1 1 * * * *     - Executes worker methods after every 24 hours