production:
  GMAP_API_FOR: http://survey.joemetric.com
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxQvE5QaufKtVxgipr7GbXN40B_edBT_Bdxi3kgTbHRiFVFqBChcwKUTMQ
  
staging:
  GMAP_API_FOR: http://joesurvey-staging.heroku.com
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxRpoafLLaB0_R5gTze-XxLIk4u3nRTuyRD4syn0yGtco6AaxFQQTeoBdA
  
gniyes_integration:
  GMAP_API_FOR: http://joesurvey-gniyes.heroku.com
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxQIyx50W_yCDeKy6J8BB65e4lnCJRQi7nUL8zXHhmuYWIlz6zacuvKBpg
  
joemetric_integration:
  GMAP_API_FOR: http://joesurvey-joemetric.heroku.com
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxSpqgpsf4TrKeOCcMY-RxAQ_ckpjBRq6Ze1wDpx4HWCTnk5wkWtTBEz7w
  
development:
  GMAP_API_FOR: http://203.129.204.130:3000
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxRl37_C5WB6CqXSo-Ce963ze3FcYBT2Q2LAGWHWrqy1ZC-WhdPe1riXzw
  
testing:
  GMAP_API_FOR: http://localhost:3000
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxRl37_C5WB6CqXSo-Ce963ze3FcYBT2Q2LAGWHWrqy1ZC-WhdPe1riXzw
  
cucumber:
  GMAP_API_FOR: http://localhost:3000
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxRl37_C5WB6CqXSo-Ce963ze3FcYBT2Q2LAGWHWrqy1ZC-WhdPe1riXzw
  