production:
  GMAP_API_FOR: http://survey.joemetric.com
  GMAP_API_KEY: ABQIAAAAhFKO9wj4BXnA9a9UFurJ7RQvE5QaufKtVxgipr7GbXN40B_edBQCFVJf9T3IPv3PwwTFMJ-II5sbwg
  
staging:
  GMAP_API_FOR: http://joesurvey-staging.heroku.com
  GMAP_API_KEY: ABQIAAAAhFKO9wj4BXnA9a9UFurJ7RRpoafLLaB0_R5gTze-XxLIk4u3nRRa0d29TJ7m-82XN01UayAHF4pxHw
  
gniyes_integration:
  GMAP_API_FOR: http://joesurvey-gniyes.heroku.com
  GMAP_API_KEY: ABQIAAAAhFKO9wj4BXnA9a9UFurJ7RQIyx50W_yCDeKy6J8BB65e4lnCJRRpgibkkuYLvaIU24C2PVW32syOoQ
  
joemetric_integration:
  GMAP_API_FOR: http://joesurvey-joemetric.heroku.com
  GMAP_API_KEY: ABQIAAAAhFKO9wj4BXnA9a9UFurJ7RSpqgpsf4TrKeOCcMY-RxAQ_ckpjBT5VnwjztLX94vW5_iUXSRSFq2WLQ
  
development:
  GMAP_API_FOR: http://203.129.204.130:3000
  GMAP_API_KEY: ABQIAAAAHnawjS0K2ifno-FFkgwCWxRl37_C5WB6CqXSo-Ce963ze3FcYBT2Q2LAGWHWrqy1ZC-WhdPe1riXzw
  
testing:
  GMAP_API_FOR: http://localhost:3000
  GMAP_API_KEY: ABQIAAAAhFKO9wj4BXnA9a9UFurJ7RTJQa0g3IQ9GZqIMmInSLzwtGDKaBTNmtCYk-fC2Aij8PHxOrrm-m1rJA
  
cucumber:
  GMAP_API_FOR: http://localhost:3000
  GMAP_API_KEY: ABQIAAAAhFKO9wj4BXnA9a9UFurJ7RTJQa0g3IQ9GZqIMmInSLzwtGDKaBTNmtCYk-fC2Aij8PHxOrrm-m1rJA
  