production:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
staging:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Staging
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
gniyes_integration:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-GniYes-Integration
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
joemetric_integration:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-JoeMetric-Integration
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
development:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-GniYes-Integration
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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

testing:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Testing
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
cucumber:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Cucumber
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  

  
  
