production:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
staging:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Staging
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
gniyes_integration:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-GniYes-Integration
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
joemetric_integration:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-JoeMetric-Integration
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
development:
<<<<<<< HEAD:config/s3.yml
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Development
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
=======
  bucket_name: 
  access_key_id: 
  secret_access_key: 
>>>>>>> 786172f2e0386e11ccd0f16dc15efe597b49b81a:config/s3.yml

testing:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Testing
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  
cucumber:
  bucket_name: JoeSurvey-Respondent-SurveyResponseFiles-Cucumber
  access_key_id: AKIAJCTYQ54LT47X2YIQ
  secret_access_key: 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
  

  
  
