development:
  :tls: true
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: noreply@joemetric.com
  :password: "odd71;humble"
  :domain: joemetric.com
production:
  :tls: true
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: noreply@joemetric.com
  :password: "odd71;humble"
  :domain: joemetric.com
#--- 
#  :user_name: your_username@gmail.com
#  :password: h@ckme
